spring:
  application:
    name: customer
  datasource:
    url: jdbc:postgresql://localhost:5432/e_comm
    username: postgres
    password: 5610
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect